Document 'ALZ-Contoso-Detailed-Network-As-Deployed' {
    Title 'ALZ Contoso Detailed Network As Deployed'

	'[[_TOC_]]'

    Section 'Introduction' {
        'This generated document shows the diagrams of all the deployed Platform Landing Zones in the tenant.'
    }
    foreach ($env in $TargetObject.Environments) {
        Section "$($env.Name) Platform ALZ's as Deployed:" -Force {
            
"* [In PDF format](./media/$($env.Prefix)-AzNetworkDiagram.pdf)
* [In PNG format](./media/$($env.Prefix)-AzNetworkDiagram.png)
* [In SVG format](./media/$($env.Prefix)-AzNetworkDiagram.svg) (Editable using Microsoft Visio when needed)"
        }
    }   

    Section "Ivory Coast Platform ALZ's as Deployed:" -Force { 
        "Coming soon!"
    }
    Section "Congo Platform ALZ's as Deployed:" -Force { 
        "Coming soon!"        
    }

    Section 'Generated by' {
        "This document was automatically generated on $(Get-Date -UFormat '%A %d %B %Y at %R (UTC%Z)')."

    }
}
